### ISSUE TITLE
Can not find the evaluation engine module.

### ISSUE THREAD

**Issue by furyphoenix** [SocialSim/SimulatorCore#2]
I can't find the evaluation engine module code in this repository. 

Would you please give  me some instructions to install the SocialSimEvaluationEngine package?

**Comment by Aganonce** [comment]
SimulatorCore is deprecated and no longer receives any kind of support from the SocialSim group. If you are looking to implement a simulator (Agent-based or otherwise) implemented in Python, I suggest you look at [AMALIA-lite](https://github.com/Aganonce/AMALIA-lite) or [mesa](https://github.com/projectmesa/mesa). Good luck!
